<a href="https://colab.research.google.com/github/shashikala16/Numpy1/blob/main/Numpylab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import numpy as np
a=np.array([1,2])
print(a)
print(a[0])
a[1]

[1 2]
1


2

In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [6]:
print(a.shape)

(2,)


In [8]:
a[0]=9
print(a)

[9 2]


In [12]:
s=np.array([[4,5,6],[7,8,9]])
print(s)

[[4 5 6]
 [7 8 9]]


In [14]:
print(s.shape)
s[0]

(2, 3)


array([4, 5, 6])

In [20]:
p=np.zeros((2,3))
print(p)

[[0. 0. 0.]
 [0. 0. 0.]]


In [22]:
s=np.full((3,4),9)
print(s)

[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [24]:
p=np.eye(4)
print(p)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [28]:
s=np.random.random((2,2))
print(s)

[[0.89192854 0.38112534]
 [0.71022928 0.27362864]]


In [38]:
a=np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
print(a)
b=a[0:2,1:3]
print(b)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]
[[2 3]
 [5 6]]


In [39]:
print(a[0,1])
b[0,0]=49
print(a[0,1])

2
49


In [41]:
print(a)
print(b)

[[ 1 49  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]
[[49  3]
 [ 5  6]]


In [43]:
row_r1 = a[1, :]     
row_r2 = a[1:2, :] 
row_r3 = a[[1], :]  
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)


[4 5 6 7] (4,)
[[4 5 6 7]] (1, 4)
[[4 5 6 7]] (1, 4)


In [45]:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[49  5  8] (3,)
[[49]
 [ 5]
 [ 8]] (3, 1)


In [48]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a.shape)
print(a[[0, 1, 2], [0, 1, 0]])
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))


(3, 2)
[1 4 5]
[1 4 5]


In [51]:
b = np.array([0, 2, 0, 1])
print(b)




[0 2 0 1]
